version: "3.8"
name: "bookstore-spring-boot-microservices"
services:
  catalog-db:
    image: mysql
    container_name: catalog-db
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: catalog
      MYSQL_ROOT_HOSTS: "%"
    ports:
      - 6666:3306
  bookstore-rabbitmq:
    image: rabbitmq:3.13.7-management
    container_name: bookstore-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 500m
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
      
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command: [ 'start-dev','--http-port=9191' ]
    container_name: keycloak
    hostname: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin1234
    ports:
      - "9191:9191"
    deploy:
      resources:
        limits:
          memory: 2gb